# Dependencies
highlighter:      rouge

gems:
  - jekyll-paginate
  - jekyll-feed

# Permalinks
permalink:              /blog/:categories/:title/
# permalink:            blog/:categories/:year/:month/:day/:title/
timezone: Asia/Shanghai
# Setup
title:            'Shang Wen Long'
name:             'Shang Wen Long'
#tagline:          ''
description:      'Programmer'
url:              'http://shangwenlong.github.io/'
baseurl: '/shangwenlong.github.io/'
# blogurl:          /blog/
# Assets
#images:         '/img'
#pdfs:           '/pdf'

author:
  name:           'Shang Wen Long'
  url:            shangwenlong.github.io
  email:          'dxcqcv@gmail.com'
  github:         'https://github.com/dxcqcv'
  facebook:       'http://www.facebook.com/shang.roy'
  twitter:        'https://twitter.com/dxcqcv'
  googleplus:     ''
  linkedin:       ''

paginate:         3
# paginate_path:    "/blog/page:num/"

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/dxcqcv/shangwenlong.github.io

# Collections
#collections:
#  - projects
#  - talks

# defaults:
#   -
#     scope:
#       path: ""
#       type: "projects" # a collection in your site, in plural form
#     values:
#       layout: "default"
